config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :apartments, only: :index do
    get :refresh, on: :collection
  end
  root 'apartments#index'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  validates :url, uniqueness: true
  validates :url, :title, :description, presence: true

  def self.pushbullet
    @pushbullet ||= Washbullet::Client.new(ENV["WASHBULLET_KEY"])
  end

  def self.refresh
    olx = AdCrawler::OLX::Parser.new.parse!
    olx.reverse.each do |ad|
      apartment = Apartment.new(ad.to_param)
      apartment.notify if apartment.save
    end
  end

  def notify
    self.class.pushbullet.devices.body['devices'].map{ |device| device['iden'] }.each do |iden|
      self.class.pushbullet.push_link iden, title, url, description
    end
  end
end

app/models/apartment_photo.rb
class ApartmentPhoto < ActiveRecord::Base
end

app/models/phone.rb
class Phone < ActiveRecord::Base
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  def index
    @apartments = Apartment.all.order('created_at')
  end

  def refresh
    Apartment.refresh
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/_form.html.haml
= form_for @apartment do |f|
  - if @apartment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@apartment.errors.count, "error")} prohibited this apartment from being saved:"
      %ul
        - @apartment.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/apartments/edit.html.haml
%h1 Editing apartment

= render 'form'

= link_to 'Show', @apartment
\|
= link_to 'Back', apartments_path

app/views/apartments/index.html.haml
%h1 Apartments

- @apartments.each do |apartment|
  .col-lg-12
    %h3= link_to "#{apartment.title} (#{apartment.service})", apartment.url
    %h5 Price: #{apartment.price} #{apartment.currency}
    %p= simple_format apartment.description

%br

app/views/apartments/new.html.haml
%h1 New apartment

= render 'form'

= link_to 'Back', apartments_path

app/views/apartments/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_apartment_path(@apartment)
\|
= link_to 'Back', apartments_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title Rent my home

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "RentMyHome", "#", :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              = link_to 'Refresh list', refresh_apartments_path
            /%li
            /  %a{:href => "#contact"} Contact
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do
          %button.close{:type => "button", :data => {:dismiss => "alert"} }
            span{:aria => {:hidden => "true"} } &times;
            span.sr-only Close
          = msg
      = yield